#!/usr/bin/env bash
set -euo pipefail

ALLOCATIONS_FILE="$HOME/.worktree/port-allocations.json"
LOCK_DIR="$HOME/.worktree/port-allocations.lock"
WORKSPACE_PATH="${WORKTREE_PATH:-$(pwd)}"
WORKSPACE_NAME="${WORKTREE_NAME:-$(basename "$WORKSPACE_PATH")}"
TTL_SECONDS=$(( 7 * 86400 ))
NOW=$(date +%s)

ports_in_use() {
  local base=$1
  local port
  for port in $base $((base+1)) $((base+2)) $((base+3)) $((base+4)); do
    lsof -iTCP:"$port" -sTCP:LISTEN -t > /dev/null 2>&1 && return 0
  done
  return 1
}

mkdir -p "$HOME/.worktree"
[ -f "$ALLOCATIONS_FILE" ] || echo '{}' > "$ALLOCATIONS_FILE"

while ! mkdir "$LOCK_DIR" 2>/dev/null; do sleep 0.1; done
trap 'rm -rf "$LOCK_DIR"' EXIT

# Migrate legacy flat format {path: port} -> {path: {port, last_used}}
ALLOCATIONS=$(jq --argjson now "$NOW" '
  to_entries | map(
    if (.value | type) == "number"
    then { key, value: { port: .value, last_used: $now } }
    else .
    end
  ) | from_entries
' "$ALLOCATIONS_FILE")

# Prune stale entries: path gone, or TTL expired and ports are idle
while IFS= read -r path; do
  port=$(echo "$ALLOCATIONS" | jq -r --arg p "$path" '.[$p].port')
  last_used=$(echo "$ALLOCATIONS" | jq -r --arg p "$path" '.[$p].last_used')
  age=$(( NOW - last_used ))

  keep=true
  [ -d "$path" ] || keep=false
  [ "$age" -gt "$TTL_SECONDS" ] && ! ports_in_use "$port" && keep=false

  if [ "$keep" = false ]; then
    ALLOCATIONS=$(echo "$ALLOCATIONS" | jq --arg p "$path" 'del(.[$p])')
  fi
done < <(echo "$ALLOCATIONS" | jq -r 'keys[]')

# Look up existing allocation or find a free port block
EXISTING=$(echo "$ALLOCATIONS" | jq -r --arg p "$WORKSPACE_PATH" '.[$p].port // empty')

if [ -n "$EXISTING" ]; then
  BASE=$EXISTING
else
  BASE=3000
  while \
    echo "$ALLOCATIONS" | jq -e --argjson b "$BASE" '[.[].port] | any(. == $b)' > /dev/null 2>&1 || \
    ports_in_use "$BASE"; do
    BASE=$(( BASE + 10 ))
  done
fi

# Upsert this workspace with a refreshed last_used
ALLOCATIONS=$(echo "$ALLOCATIONS" | jq \
  --arg p "$WORKSPACE_PATH" --argjson port "$BASE" --argjson now "$NOW" \
  '.[$p] = { port: $port, last_used: $now }')

echo "$ALLOCATIONS" > "${ALLOCATIONS_FILE}.tmp"
mv "${ALLOCATIONS_FILE}.tmp" "$ALLOCATIONS_FILE"

FRONTEND_PORT=$BASE
DB_PORT=$(( BASE + 1 ))
DOZZLE_PORT=$(( BASE + 2 ))
BACKEND_PORT=$(( BASE + 3 ))

cat > .env.worktree << EOF
# Generated by .worktree/allocate-ports.sh; do not edit by hand
WORKSPACE_NAME=${WORKSPACE_NAME}
FRONTEND_PORT=${FRONTEND_PORT}
DB_PORT=${DB_PORT}
DOZZLE_PORT=${DOZZLE_PORT}
BACKEND_PORT=${BACKEND_PORT}
DYNAMO_VOLUME_NAME=dynamodb-data-${WORKSPACE_NAME}
EOF

echo "Workspace ${WORKSPACE_NAME}: ports ${BASE}-$(( BASE + 3 ))"
